export const GENRES = [
    {val: "POP", genre: "POP" ,joeColor: "#71dfd4"},
     {val: "HIP_HOP_RAP", genre: "RAP" ,joeColor: "#dbb677"},
    {val: "DANCE", genre: "DANCE",joeColor: "#d7eaf5"},
    {val: "ELECTRONIC", genre: "ELECTRONIC" ,joeColor: "#24160c"},
     {val: "SOUL_RNB", genre: "SOUL" ,joeColor: "#e8c4aa"},
    {val: "ROCK", genre: "ROCK" ,joeColor: "#fc7f48"},
     {val: "LATIN", genre: "LATIN" ,joeColor: "#d3d9dd"},
     {val: "FILM_TV", genre: "FILM" ,joeColor: "#e2c579"},
    {val: "COUNTRY", genre: "COUNTRY" ,joeColor: "#8798b8"},
     {val: "AFRO_BEATS", genre: "AFRO" ,joeColor: "#3c2633"},
     {val: "WORLDWIDE", genre: "WORLDWIDE" ,joeColor: "#437fb9"},
     {val: "REGGAE_DANCE_HALL", genre: "REGGAE",joeColor: "#d3a060"},
    {val: "HOUSE", genre: "HOUSE" ,joeColor: "#f0d6ba"},
     {val: "K_POP", genre: "KPOP" ,joeColor: "#b48f9d"},
     {val: "FRENCH_POP", genre: "FRENCH" ,joeColor: "#d5aa00"},
     {val: "REG_MEXICO", genre: "MEXICO" ,joeColor: "#cf402a"},
    {val: "ALTERNATIVE", genre: "ALTERNATIVE" ,joeColor: "#e96750"},
     {val: "SINGER_SONGWRITER", genre: "SINGER",joeColor: "#ed8c7f"}
]